### ISSUE TITLE
Legislativní dokumenty: temata ve fasetě 

### ISSUE THREAD

**Issue by black23** [moravianlibrary/Knihovny.cz#10]
Názvy témat jsou zatím bez diakritiky:
![obrazek](https://user-images.githubusercontent.com/5516936/148360266-f30e89fd-74f7-4f09-a8c1-c07195cfbf12.png)

**Comment by xmorave2** [comment]
Temata u legislativních dokumentů byla z indexu odstraněna, protože se kryla s typem dokumentu, jen byla bez diakritiky.
