### ISSUE TITLE
Odeslání položky mailem

### ISSUE THREAD

**Issue by black23** [moravianlibrary/Knihovny.cz#11]
Pokud se tato funkce bude používat na produkci, měl by se přetextovat mail. Také by se měla vypnout možnost vyplnění pole "Od koho", protože to dělá z mailu nedůvěryhodný případ, který může mít problém projít přes spamové ochrany.
![obrazek](https://user-images.githubusercontent.com/5516936/148361207-e65b4320-a139-41fd-9aac-de15e32872e7.png)

**Comment by xmorave2** [comment]
Jak by měl text toho e-mailu vypadat?

**Comment by black23** [comment]
Například takto:
Tento e-mail by odeslán z portálu Knihovny.cz. Pokud jste si níže uvedené informace neobjednal(a) nebo nezaslal(a) můžete tuto zprávu smazat, protože byla pravděpodobně doručena omylem. Text je generován automaticky, na zprávu neodpovídejte.

Zpráva, kterou vyplnil odesílatel:
Lorem ipsum (zkráceně lipsum) je označení pro standardní pseudolatinský text užívaný v grafickém designu a navrhování jako demonstrativní výplňový text při vytváření pracovních ukázek grafických návrhů (např. internetových stránek, rozvržení časopisů či všech druhů reklamních materiálů). Lipsum tak pracovně znázorňuje text v ukázkových maketách (tzv. mock-up) předtím, než bude do hotového návrhu vložen smysluplný obsah. 

Odkaz na záznam(y), které chtěl odesílatel sdílet.


***********************************************************
www.knihovny.cz: všechny české knihovny na jednom místě.

**Comment by vodomilka** [comment]
Dobrý den, odeslání položky ze schránky mailem se mi opakovaně nepodařilo, ani s odstupem pár dní. Hlásí mi to při odeslání chybu: Verification failed for <no-reply@knihovny.cz> Unrouteable address Sender verification failed
Jako adresáta uvádím svou gmailovou adresu, jako odesílatele svou pracovní, obě jsou tedy funkční.

**Comment by xmorave2** [comment]
Vyřešeno ve vydání [Knihovny.cz 2.0.6](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.6)
