### ISSUE TITLE
Linky na prodloužení registrace a k uhrazení poplatků

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#12]
V záložce Moje knihovny by se hodily odkazy na prodloužení registrace u účtů v knihovnách, kde registrace vypršela, a k uhrazení poplatků za rezervace.

V patičce portálu chybí odkaz na https://www.knihovny.cz/Portal/Page/moznosti-prihlaseni-a-registrace

**Comment by martinkrcal** [comment]
Máme odkaz pouze od 6 knihoven, které nám poslaly odkaz na registraci. Seznam není aktuální, proto jsme ho skryli. V současném počtu knihoven se nedá udržovat.

**Comment by xmorave2** [comment]
Vydáno v https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.1.10
