### ISSUE TITLE
Tip: změna z rezervace k vyzvednutí v knihovně na doručení přes Získej  

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#13]
Změna z rezervace k vyzvednutí v knihovně na dodání přes Získej obnáší nyní zrušení rezervace mimo CPK a nové zadání v CPK dodání přes Získej. Navrhuji v CPK doplnit funkci změny rezervace na dodání přes Získej.

**Comment by martinkrcal** [comment]
V současnosti to nelze z technických důvodů na straně knihovních systémů realizovat.
