### ISSUE TITLE
Link na umístění na regálu

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#14]
V záložce Rezervace a objednávky by se hodil link na umístění na regálu.

**Comment by martinkrcal** [comment]
V současnosti tuto informaci od knihoven nemáme.

**Comment by jiripavlik88** [comment]
Díky za prověření, zobrazení umístění na regále zůstane asi mezi benefity vlastního OPAC. Příklad z JVKCB:

https://katalog.cbvk.cz/arl-cbvk/cs/detail-cbvk_us_cat-1095683-A-odkud-bych-asi-tak-byl/

-> Kde najdu
