### ISSUE TITLE
Rozbitý "Můj účet"

### ISSUE THREAD

**Issue by jandera** [moravianlibrary/Knihovny.cz#17]
Po přihlášení přes IdP Knihovny AV ČR a kliknutí na https://cpk-front.mzk.cz/MyResearch/Home?redirect=0 se zobrazí "Whoops\Exception\ErrorException thrown with message "Undefined array key "fullname""

Stacktrace:
#25 Whoops\Exception\ErrorException in /var/www/knihovny-cz/module/VuFind/src/VuFind/ILS/Driver/Aleph.php:1547
#24 Whoops\Run:handleError in /var/www/knihovny-cz/module/VuFind/src/VuFind/ILS/Driver/Aleph.php:1547
#23 VuFind\ILS\Driver\Aleph:getMyProfileDLF in /var/www/knihovny-cz/module/VuFind/src/VuFind/ILS/Driver/Aleph.php:1459
#22 VuFind\ILS\Driver\Aleph:getMyProfile in /var/www/knihovny-cz/module/VuFind/src/VuFind/ILS/Driver/Aleph.php:1582
#21 VuFind\ILS\Driver\Aleph:patronLogin in /var/www/knihovny-cz/module/VuFind/src/VuFind/ILS/Driver/MultiBackend.php:1449
#20 call_user_func_array in /var/www/knihovny-cz/module/VuFind/src/VuFind/ILS/Driver/MultiBackend.php:1449
#19 VuFind\ILS\Driver\MultiBackend:callMethodIfSupported in /var/www/knihovny-cz/module/VuFind/src/VuFind/ILS/Driver/MultiBackend.php:1119
#18 VuFind\ILS\Driver\MultiBackend:__call in /var/www/knihovny-cz/module/VuFind/src/VuFind/ILS/Connection.php:1109
#17 call_user_func_array in /var/www/knihovny-cz/module/VuFind/src/VuFind/ILS/Connection.php:1109
#16 VuFind\ILS\Connection:__call in /var/www/knihovny-cz/module/VuFind/src/VuFind/Auth/ILSAuthenticator.php:131
#15 VuFind\Auth\ILSAuthenticator:storedCatalogLogin in /var/www/knihovny-cz/vendor/ocramius/proxy-manager/src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php:57
#14 ProxyManagerGeneratedProxy\__PM__\VuFind\Auth\ILSAuthenticator\Generatedd593bb4eee6940f8f57d5b9f741ffe14:storedCatalogLogin in /var/www/knihovny-cz/module/VuFind/src/VuFind/View/Helper/Root/Auth.php:131
#13 VuFind\View\Helper\Root\Auth:getILSPatron in /var/www/knihovny-cz/themes/KnihovnyCz/templates/myresearch/menu.phtml:3
#12 include in /var/www/knihovny-cz/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php:500
#11 Laminas\View\Renderer\PhpRenderer:render in /var/www/knihovny-cz/module/VuFind/src/VuFind/View/Helper/Root/Context.php:102
#10 VuFind\View\Helper\Root\Context:renderInContext in /var/www/knihovny-cz/themes/KnihovnyCz/templates/myresearch/checkedout-all.phtml:67
#9 include in /var/www/knihovny-cz/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php:500
#8 Laminas\View\Renderer\PhpRenderer:render in /var/www/knihovny-cz/vendor/laminas/laminas-view/src/View.php:200
#7 Laminas\View\View:render in /var/www/knihovny-cz/vendor/laminas/laminas-view/src/View.php:229
#6 Laminas\View\View:renderChildren in /var/www/knihovny-cz/vendor/laminas/laminas-view/src/View.php:193
#5 Laminas\View\View:render in /var/www/knihovny-cz/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php:104
#4 Laminas\Mvc\View\Http\DefaultRenderingStrategy:render in /var/www/knihovny-cz/vendor/laminas/laminas-eventmanager/src/EventManager.php:319
#3 Laminas\EventManager\EventManager:triggerListeners in /var/www/knihovny-cz/vendor/laminas/laminas-eventmanager/src/EventManager.php:171
#2 Laminas\EventManager\EventManager:triggerEvent in /var/www/knihovny-cz/vendor/laminas/laminas-mvc/src/Application.php:366
#1 Laminas\Mvc\Application:completeRequest in /var/www/knihovny-cz/vendor/laminas/laminas-mvc/src/Application.php:347
#0 Laminas\Mvc\Application:run in /var/www/knihovny-cz/public/index.php:71"
![CPK-front-moje_konto](https://user-images.githubusercontent.com/18327175/148916351-f2ded93c-0a50-499e-b874-30e196ee0ec4.jpg)

**Comment by xmorave2** [comment]
Vyřešeno ve vydání [Knihovny.cz 2.0.3](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.3fixVersion)
