### ISSUE TITLE
Zpět na výsledky vyhledávání

### ISSUE THREAD

**Issue by HankaHornychova** [moravianlibrary/Knihovny.cz#18]
Nad úplným zobrazením záznamu ve výsledcích chybí šipka "Zpět na výsledky vyhledávání".

**Comment by xmorave2** [comment]
Vyřešeno ve vydání [Knihovny.cz 2.0.3](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.3fixVersion)
