### ISSUE TITLE
Tlačítko E-verze

### ISSUE THREAD

**Issue by HankaHornychova** [moravianlibrary/Knihovny.cz#19]
Tlačítko E-verze je stále aktivní (probarvené), i když u dokumentu není elektronická verze dostupná.
Příklad:
https://cpk-front.mzk.cz/Record/nkp.NKC01-003315254
Po kliknutí na tlačítko se objeví prázdný řádek.

V předchozí verzi portálu bylo tlačítko v tomto případě neaktivní (šedé).
Příklad:
https://www.knihovny.cz/Record/svkhk.HKA01-001008632

**Comment by xmorave2** [comment]
Vyřešeno ve vydání [Knihovny.cz 2.0.3](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.3fixVersion)

**Comment by vojtisev** [comment]
Ještě ke tlačítku E-verze: nešlo by ošetřit situaci, kdy těch (asi stejných) verzí je u záznamu několik a já pak jako uživatel nevím, jaký je rozdíl a co si mám vlastně vybrat?

![Tropical snow  Knihovny cz 2022-01-19 08_39_24](https://user-images.githubusercontent.com/11600358/150094607-138b2b0a-d31b-4f95-8299-30e0104f13da.png)

**Comment by xmorave2** [comment]
@vojtisev Vytvořil jsem samostatnou issue #28
