### ISSUE TITLE
Ve facetě "Instituce" chybí nástrojová lišta

### ISSUE THREAD

**Issue by jandera** [moravianlibrary/Knihovny.cz#20]
Ve facetě "Instituce" chybí nástrojová lišta, zejména oblíbený domeček pro automatické zahrnutí pouze knihoven u kterých jsem registrovaný.

**Comment by PetraZabickova** [comment]
s funkcionalitou do budoucna počítáme, ale bude to vyřešené trochu jinak

**Comment by xmorave2** [comment]
Vydáno ve verzi https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.1.7
