### ISSUE TITLE
Zjistit dostupnost - preferovat moje knihovny

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#21]
Ve Zjistit dostupnost - Plný text dostupný by bylo vhodné zobrazit nejdříve dostupnost v knihovách, ze kterých má uživatel propojené identity. Odděleně pak v dalších knihovnách, kde uživatel bude plný text poptávat nejspíše přes e-kopie Získej.

**Comment by xmorave2** [comment]
Vyřešeno ve vydání [Knihovny.cz 2.0.4](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.4)
