### ISSUE TITLE
Po přihlášení není vidět jméno v horní liště

### ISSUE THREAD

**Issue by HankaHornychova** [moravianlibrary/Knihovny.cz#23]
Po přihlášení nevidí uživatel jméno v horní bílé liště.
Zobrazí se tlačítko Můj účet.

Jako kontrola, že přihlášení proběhlo úspěšně, je lepší jméno v pravém horním rohu (nebo někde v těch místech).

**Comment by xmorave2** [comment]
Vyřešeno ve vydání [Knihovny.cz 2.0.3](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.3fixVersion)

**Comment by vojtisev** [comment]
> Vyřešeno ve vydání [Knihovny.cz 2.0.3](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.3fixVersion)

Vyzkoušeno, funguje.
