### ISSUE TITLE
Pokročilé vyhledávání

### ISSUE THREAD

**Issue by HankaHornychova** [moravianlibrary/Knihovny.cz#24]
Pokročilé vyhledávání je prezentováno linkem Pokročilé.
Link je umístěn vedle vyhledávacího řádku a je tam přítomen při všech akcích.

V původní verzi bylo Pokročilé vyhledávání umístěno pod vyhledávacím řádkem (na úvodní straně) a vedle vyhledávacího řádku (na stránce seznamu výsledků).

Není zřejmé, co znamená Pokročilé - doplnit na Pokročilé vyhledávání.

**Comment by martinkrcal** [comment]
Diskutovali jsme, přijde nám to hodně dlouhé a u vyhledávacího formuláře nám přijde logické, že jde o vyhledávání. Nechali bychom v aktuální podobě.
