### ISSUE TITLE
Problém s načítáním obálek v historii výpůjček.

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#25]
U některých titulů v historii se nenačítají obálky, screenshoty s tituly přikládám.

![historie-err1](https://user-images.githubusercontent.com/16347996/149955247-c9a90fca-b98c-490b-916d-c3f33082c52c.jpg)
![hisrorie-err2](https://user-images.githubusercontent.com/16347996/149955265-8cb66639-2adb-40cc-b906-57cf56a2a937.jpg)

**Comment by xmorave2** [comment]
Zdá se, že se jedná o dokumenty, ke kterým nemáme záznamy. Obálku sice najít nedokážeme, ale neměl by tam zůstavat viset loader, na to se budeme muset podívat.

**Comment by jandera** [comment]
Také někdy skončí timeoutem, myslím, že je tam nastaveno 10 sec., ale s mým téměř 300 položkovým seznamem někdy neprolezu.

**Comment by xmorave2** [comment]
Vyřešeno ve vydání [Knihovny.cz 2.0.4](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.4)
