### ISSUE TITLE
Komplikovaný název stránky v záhlaví

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/Knihovny.cz#26]
Do názvu otevřeného panelu se propisuje částečně vyhledávací dotaz, je to detail, ale vypadá to podivně.

![Výsledky vyhledávání - inspiration quot;eknihy_ke_stazeni quot;  Knihovny cz 2022-01-19 08_26_10](https://user-images.githubusercontent.com/11600358/150092439-946bc24e-c012-427a-8f7a-cbc009aa2502.png)

**Comment by michalMZK** [comment]
Ještě doplňuji: když si otevřu záznam konkrétního titulu, název stránky začíná vždy "Jednotky: …" / "Holdings: …". A zůstává to tam i když se přepnu do jiné záložky (Koupit, Metadata, Instituce).
