### ISSUE TITLE
RSS z výsledků vyhledávání je rozbité

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/Knihovny.cz#27]
![httpscpk-front mzk czSearchResultslookfor=inspiration3A22eknihy_ke_stazeni22 type=AllFields view=rss 2022-01-19 08_30_18](https://user-images.githubusercontent.com/11600358/150093194-3d76bedf-f4d8-4a69-8fd8-e22e169563b6.png)

![Snímek obrazovky 2022-01-19 v 9 29 46 2022-01-19 08_30_01](https://user-images.githubusercontent.com/11600358/150093090-08688f86-ea05-4e75-b965-0dfaf5410f86.png)

**Comment by xmorave2** [comment]
Vyřešeno ve vydání [Knihovny.cz 2.0.4](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.4)
