### ISSUE TITLE
Verification failed for <no-reply@knihovny.cz> Unrouteable address Sender verification failed 

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#29]
Chyba při zasílání vybraných výsledků vyhledávání e-mailem.

![email-err](https://user-images.githubusercontent.com/16347996/151146524-09fa9e26-3821-4193-ad53-4eb9693b1454.jpg)

**Comment by jiripavlik88** [comment]
Nejspíš obdobný problém  jako u #11

**Comment by xmorave2** [comment]
Vyřešeno ve vydání [Knihovny.cz 2.0.6](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.6)
