### ISSUE TITLE
Dummy v Moje knihovny

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#3]
Identity Google a mojeID se zobrazují v Moje Knihovny jako Dummy.

**Comment by xmorave2** [comment]
Vyřešeno

**Comment by jandera** [comment]
Já tedy u svého účtu stále u mojeID vidím Dummy a pokud se přihlásím přes mojeID, tak se nepřihlásím do "svého" účtu, kde mám propojené identity s KNAV a MZK a práve mojeID. Narozdíl od stávající verze tam jsou ještě zobrazena systémová ID
![identity](https://user-images.githubusercontent.com/18327175/149066890-6f490859-2048-4967-ad71-35370f42c19d.png)
![identity_knihovny](https://user-images.githubusercontent.com/18327175/149066908-03905e01-887b-4c62-b97a-fa8d53314bb6.png)
.

**Comment by jiripavlik88** [comment]
V Moje knihovny se mojeID a Google už nezobrazují, super. 

Proč v Propojené identity v pilotní verzi jsou ID uživatele namísto log poskytovatelů identit?  Díky za postřeh, Tomáši.

**Comment by jandera** [comment]
U mne v "Moje knihovny" stále vidím mojeID jako Dummy (nemám tam propojený Google, tak to nic jiného být nemůže) a vidím to tak i ve "Výpůjčky" tam to pod Dummy hlásí ještě "No suitable backend driver found", stejně tak v "Historie výpůjček" a "Rezervace a objednávky".  U "Pokuty a poplatky" je to tam bez hlášky, jen Dummy.

**Comment by xmorave2** [comment]
Problém byl v datech, která vznikla ještě před nasazením aktuální verze. Nyní by to mělo být opravené a "Dummy" by se nemělo nikde zobrazovat. Zároveň už by měli být názvy identit správně (tedy Google místo google). Loga jendotlivých institucí budou přidána a id uživatele odstraněna a to pravděpodobně brzy.

**Comment by jiripavlik88** [comment]
Je to prkotina, ale správně je mojeID :-) Viz https://www.mojeid.cz/cs/

**Comment by xmorave2** [comment]
Je to prkotina, ale měli bychom to mít správně, opravíme.

**Comment by jandera** [comment]
Dummy už se nikde nezobrazuje, ale stále není propojeno mé mojeID s mým účtem, kde mám propojené ještě KNAV a MZK, hlásí mi to, "Nyní nejste na portálu přihlášen v žádné knihovně....", ale na produkční verzi to normálně funguje. Asi bych mohl tuto identitu odstranit a znovu přidat, ale tohle může být pro uživatele problém, pokud se primárně do svého účtu přihlašuje přes mojeID a přihlašování přes identitu své knihovny nepoužívá.

**Comment by xmorave2** [comment]
V tuto chvíli by odebrání a znovu propojení mojeID pomohlo, ale už pracujeme na opravě, která si poradí i s touto situací. Až bude nasazeno, dáme zase vědět.

**Comment by xmorave2** [comment]
Vyřešeno ve vydání [Knihovny.cz 2.0.3](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.3fixVersion)
