### ISSUE TITLE
Schránka není vázána na účet

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#30]
Schránka není vázána na účet. Dokumenty uložené do schránky na jednom zařízení nejsou ve schránce po přihlášení na jiném zařízení. Dokumenty zůstávají ve schránce po odhlášení.

Schránka by měla být vázána na účet uživatele spíše než na session.

**Comment by zabak** [comment]
Schránka je dočasná, jde o vlastnost vufindu. Pokud chceš něco vázaného na účet, použij oblíbené.
