### ISSUE TITLE
Chybějící články pro EDD

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#31]
Miroslava Strakatá vydala v sérii "Využití vzdělávacích programů EU" 5 či 6 článků. CPK dohledá pouze jeden článek ze série.

Vyhledávané termíny: "(Název, edice:Využití vzdělávacích programů EU A Autor, korporace, akce:Strakatá)"

**Comment by zabak** [comment]
@jiripavlik88 ve které z portálem sklízených databází ty ostatní články jsou?

**Comment by jiripavlik88** [comment]
Série vycházela v časopise Řízení školy. Miroslavě Strakaté ve 2013 - 2015 vyšlo kolem 25 článků v časopisech Řízení školy, Očekávané výstupy v praxi mateřské školy, Nápadník pro MS, Rádce předškolního vzdělávání, Výběr z aktuálních školských témat. CPK dohledá jeden. To je pro EDD problém.

**Comment by PetraZabickova** [comment]
Zrovna pro EDD to problém vůbec není, protože EDD bude umožnovat čtenáři, aby si zadal článek přes vlastní formulář pokud k němu metadata nenajde.

**Comment by zabak** [comment]
@jiripavlik88 ještě doplním: CPK zpřístupňuje jen to, co existuje v nějakých databázích, nic navíc nevytváříme. Ten jeden záznm je z bibliografie PKJAK. Tj. pokud chceš aby byly ty články dohledatelné, měli by je zpracovat do své bibliografie.

**Comment by jiripavlik88** [comment]
Tady by se hodila integrace CPK s Ptejte se knihovny - na dotaz k dohledání článků během dne z PSK dorazila odpověď.
Formulář k zadání EDD požadavku, když CPK nemůže dohledat metadata požadovaného dokumentu, bude bezva.
