### ISSUE TITLE
Intergrace PSK

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#32]
V CPK by se hodila integrace Ptejte se knihovny pro případ, že uživatel nedohledá, co potřenuje.

**Comment by xmorave2** [comment]
Bude řešeno v rámci koncepce rozvoje portálu Knihovny.cz v roce 2023

**Comment by xmorave2** [comment]
Vydáno ve verzi https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.1.6
