### ISSUE TITLE
Nelze najít některé eKnihy s filtrem plný text

### ISSUE THREAD

**Issue by jandera** [moravianlibrary/Knihovny.cz#34]
Pokud ve vyhledávání v zahraničních zdrojích zapnu filtr plný text, nenajdu některé eKnihy, např.. "DNA Methylation in Plants" - https://cpk-front.mzk.cz/EDS/Search?lookfor=%22DNA+Methylation+in+Plants%22&type=AllFields&filter%5B%5D=LIMIT%7CFT%3Ay&limit=20 pokud filtr vypnu mám ji na 10 místě výsledků a je plnotextově dostupná u KNAV, NK a NTK.

**Comment by PetraZabickova** [comment]
Filtr, který zapíná Fulltexty ovlivňujeme exporty, které Ebscu zasíláme s exportů z linkserverů. Poslední aktualizace proběhla 5. ledna. V balíčku námi zaslaných dat je i export z KNAV, který obsahuje záznam Vámi uvedené E-knihy.  Zdá se tedy, že se to spárovalo správně. 

Ale filtery v Ebscu fungují někdy komplikovaně kvůli deduplikaci, která v Ebscu probíhá v reálném čase. Daný záznam pochází z více zdrojů (balíčků). Pro různé dotazy a různě upřesněné dotazy vyhraje vždy jiný zdroj. Když se podíváte zde:

https://cpk-front.mzk.cz/EDS/Search?lookfor=1-60692-051-0&type=AllFields&limit=20

Tak je vidět, že danou e-knihu mají 3x, ale v některých zdrojích je  do fitrů zařazená jako E-kniha jindy se jedná o Elektronický zdroj. 

Při různých dotazech vyhraje nemusí vyhrát ten stejný záznam, který se zobrazí a má konkrétní filter. Ve chvíli, kdy dojde k zúžení nebo se dotaz jiným způsobem přeformuluje, tak přijdou nové výsledky. Bezpečnější je v případě použití EBSCA nepoužívat kombinované filtery.

**Comment by zabak** [comment]
Na naší straně s tím nejde nic udělat, zavírám.
