### ISSUE TITLE
Zahraniční zdroje - zobrazit v EDS

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/Knihovny.cz#38]
K čemu má sloužit "zobrazit v EDS" u jednotlivého vyhledaného záznamu v CI - zahraniční zdroje?
![CIi-zobrazit_v_EDS](https://user-images.githubusercontent.com/15088603/152003800-11abc3bb-bf13-4dbb-9c24-aeade31e3327.jpg)
?

**Comment by martinkrcal** [comment]
Odkaz na EDS odstraníme.

**Comment by xmorave2** [comment]
Odkaz odstraněn ve vydání [Knihovny.cz 2.0.6](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.6)
