### ISSUE TITLE
Zahraniční zdroje - zpět na výsledky

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/Knihovny.cz#39]
Plánujete v CI zahraniční zdroje také navigaci ve výsledcích jako je v národních zdrojích?
![zpet_na_vysledky](https://user-images.githubusercontent.com/15088603/152004388-213479a2-2f03-4342-82f8-cb13383dbf65.jpg)
![zpet_na_vysledky_2](https://user-images.githubusercontent.com/15088603/152005126-bf0990f5-250a-4925-96de-9cc549136774.jpg)
?

**Comment by xmorave2** [comment]
Vyřešeno ve vydání [Knihovny.cz 2.0.6](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.6)
