### ISSUE TITLE
Nedotahují se obálky s vlastním identifikátorem

### ISSUE THREAD

**Issue by jandera** [moravianlibrary/Knihovny.cz#41]
Nedotahují se obálky s vlastním identifikátorem sigla-sysno, např: https://cpk-front.mzk.cz/Record/knav.KNA01-001003132
https://www.obalkyknih.cz/view?nbn=aba007-001003132 jedná se převážně o historický fond zahraniční produkce, tedy bez čČNB.

**Comment by xmorave2** [comment]
Vydáno https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.1.6
