### ISSUE TITLE
Chci vypůjčit - pořadí ve frontě

### ISSUE THREAD

**Issue by PetraZabickova** [moravianlibrary/Knihovny.cz#43]
Viz https://github.com/moravianlibrary/CPK/issues/199[]

(https://user-images.githubusercontent.com/15088603/152014974-2cd382a0-f8f2-40d9-84b1-bc043d89cfe0.jpg) - pořadí ve frontě tentokrát chybí úplně.

**Comment by xmorave2** [comment]
Vydáno ve verzi 2.1.4: https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.1.4
