### ISSUE TITLE
Chci vypůjčit - více bibliografických údajů v objednávkovém formuláři

### ISSUE THREAD

**Issue by PetraZabickova** [moravianlibrary/Knihovny.cz#44]
V kartě "chci vypůjčit" by mohlo být více bibl. údajů než jen název a větším písmem.
Chybí návrat na zpět na záznam, pokud si objednávku rozmyslím.

**Comment by xmorave2** [comment]
Opraveno ve verzi 2.1.2 https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.1.2
