### ISSUE TITLE
Inspirace "Obor"

### ISSUE THREAD

**Issue by xmorave2** [moravianlibrary/Knihovny.cz#45]
[jiripavlik88](https://github.com/jiripavlik88) commented [22 days ago](https://github.com/moravianlibrary/Knihovny.cz/issues/5#issuecomment-1019529984)

Obor, Zobrazit všechny - nevede na žádné dokumenty pro inspiraci.

**Comment by xmorave2** [comment]
Inspirační panel "Obor" opraven ve vydání [Knihovny.cz 2.0.7](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.7)

**Comment by jiripavlik88** [comment]
Ve 2.0.7 se panel Obor liší ve české a v anglické verzi. V obou verzích vypadá zajímavě :-) Anglická verze je tedy česky, ale je pěkně funkční. Oborové hledání v národních zdrojích je pěkné, v zahraničních zdrojích chybí.

**Comment by xmorave2** [comment]
@jiripavlik88 Jak konkrétně se prosím liší panel Obor mezi jazykovými verzemi?

V zahraničních zdrojích nelze vyhledávání podle oboru vytvořit. Je to postavené na konspektu a ten EDS neposkytuje.

**Comment by jiripavlik88** [comment]
Spíše se panel Obor mění po přihlášení, koukám. Přikládám screenshoty. 
![obor-cz jog](https://user-images.githubusercontent.com/16347996/154036098-d82ed38d-cd81-45c1-bff5-337e26deab25.jpg)
![obor-en](https://user-images.githubusercontent.com/16347996/154036103-2ca56005-18de-43ef-bd2b-3e91d8b2e558.jpg)

**Comment by PetraZabickova** [comment]
Panel Obor je funkční. Anglickou verzi v nejbližší době nechystáme. Issue zavírám, na nové problémy je potřeba případně založit nové issue.
