### ISSUE TITLE
seznamy čtení dětem nefungují

### ISSUE THREAD

**Issue by jandera** [moravianlibrary/Knihovny.cz#46]
Seznamy na https://ctenidetem.knihovny.cz/ nefungují pokud je link konstuován jako dotaz, např:
1. třída https://www.knihovny.cz/Inspiration/First_class_books?utm_source=ctenidetem-knihovny-cz&utm_medium=portal&utm_campaign=ctenidetem
2. třída https://www.knihovny.cz/Inspiration/second_class_books?utm_source=ctenidetem-knihovny-cz&utm_medium=portal&utm_campaign=ctenidetem
atd.
Tam kde je to klasické URL, tak to funguje:
http://knihovny.cz/Inspiration/preschool
https://www.knihovny.cz/inspirace/geneticka_metoda_cteni
https://www.knihovny.cz/inspirace/poezie_pro_deti
atd.

**Comment by xmorave2** [comment]
Opraveno ve vydání [Knihovny.cz 2.0.12](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.12)
