### ISSUE TITLE
Ziskej API input error: Library with sigla "ABA013" is not active

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#47]
U knihy Ztracen na Hedvábné stezce - https://www.knihovny.cz/Record/cbvk.cbvk_us_cat*1111447 - požadavek na výpůčku Získej do NTK končí s chybou:  Ziskej API input error: Library with sigla "ABA013" is not active
![HedvabnaStezskaErr](https://user-images.githubusercontent.com/16347996/157065466-a2765879-4f71-4483-8397-d0916fd076e4.jpg)

**Comment by jiripavlik88** [comment]
Jde o chybu při zadání požadavku Získej, kdy je vybraná instituce bez zapojení v Získej nebo bez jednotek. Požadavek Získej na uvedenou knihu při vybrané jiné instituci, např. https://www.knihovny.cz/Record/mkklat.252682, je v pořádku.

**Comment by xmorave2** [comment]
V dnešním vydání jsem udělali úpravu, která zobrazuje o něco srozumitelnější chybová hlášení. V tomto konkrétním případě, totiž Získej vracelo http kód, který podle dokumentace znamená, že knihovna není aktivní. Ale konkrétní chyba byla ve skutečnosti stejná jako když nastane 422 - nyní zobrazujeme v chybovém hlašení konkrétní chybu kterou dostaneme v body od API Získej, bez ohledu na http status code. Nicméně důvod, proč ta objednávka nelze vytvořit je ten, že Získej neumí vytvářet objednávky, pokud ten základní záznam, u kterého čtenář objednávku vytváři, nemá jednotky.

**Comment by jiripavlik88** [comment]
Vidím hlášku: Ziskej API response error: "422 UNPROCESSABLE ENTITY: {"error":"Invalid request: cannot create ticket due to invalid main record in CPK such as missing unit ids etc."} "

Z ní by čtenář mohl vyrozumět, že objednávku Získej má zadat tak, že vybere některou z institucí s jednotkami. Díky.

Bylo by možné problém dále u CPK ošetřit tak, že objednávku bude CPK posílat Získej za některou z institucí, která má jednotky? Čili čtenář nebude potřebovat při zadání objednávky Získej vybírat některou z institucí s jednotkami, CPK při odeslaní požadavku na API Získej automaticky některou z institucí s jednotkami vybere.

**Comment by xmorave2** [comment]
Upravit Knihovny.cz aby podstrkovali jiný záznam, který jednotky má by teoreticky bylo možné. Ale není to pro nás v tuto chvíli priorita, dělali bychom to až někdy v budoucnu.

Další možnost je, že se to upraví na straně Získej, což je řešení, které je z našeho pohledu systémovější. 

Pokud tomu dobře rozumím, tak když Získej od nás dostane požadavek, tak dohledává dostupnosti pro propojené dokumenty z dalších knihoven, aby mohlo zvolit, odkud se dokument objedná. Nicméně v případě, že ten primární dokument jednotky nemá, tak se toto prohledávání neprovádí a ticket se nevytvoří.

Proto by nám přišlo vhodnější, řešit to na straně Získej.

**Comment by jiripavlik88** [comment]
Díky za komentář, probereme ošetření problému na straně Získej.

**Comment by jiripavlik88** [comment]
Připravujeme ošetření na straně Získej.
