### ISSUE TITLE
Chybějící tlačítka Uhradit, Stornovat, Reklamovat po vytvoření objednávky Získej na mobilu

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#50]
Po vytvoření objednávky Získej na mobilu se nezobrazí tlačítka Uhradit objednávku, Stornovat objednávku, Reklamovat objednávku. Zobrazí se pouze tlačítko Detail objednávky.

Navrhuji upravit, po vytvoření objednávky na mobilu zobrazovat tlačítka Uhradit objednávku, Stornovat objednávku, Reklamovat objednávku obdobně jako při vytvoření objednávky na desktopu, notebooku.

![IMG_6622](https://user-images.githubusercontent.com/16347996/160831615-bced4e0f-ccd4-4af1-96ba-fc5e41816b3e.jpg)

**Comment by martinkrcal** [comment]
Díky za návrh. Toto je obrazovka hned po objednávce, kde je pro uživatele důležitá ta informace o úspěšně vytvořené objednávce. Tlačítka by pak měla být v detailu objednávky. Do budoucna se na to můžeme podívat, ale přemýšlel bych nad celým procesem komplexně. Logicky mi tam sedí pouze to uhradit, pokud se tak již nestalo. Storno a reklamace se řeší spíše později, když se něco nepovede. Prozatím odkládáme na později.

**Comment by jiripavlik88** [comment]
Mohli byste prozatím upravit text:

Dokončení objednávky Získej č. xxxxx
Objednávka prostřednicvím služby Získej byla úspěšně vytvořena.

na:

Dokončení objednávky Získej č. xxxxx
Objednávka prostřednicvím služby Získej byla úspěšně vytvořena, v detailu objednávky proveďte úhradu, prosím.

**Comment by martinkrcal** [comment]
Máš pravdu, dali jsme do fronty a uděláme to. Přidáme tlačítko uhradit.

**Comment by jiripavlik88** [comment]
Super, díky.

**Comment by jiripavlik88** [comment]
Na mobilu a tabletu vypadaji tlacitka pro uhradu a storno po objednani dobre 👍🏻 Otestuju jeste na notebooku.

**Comment by jiripavlik88** [comment]
Na notebooku taky bezva. Díky za úptavu!
