### ISSUE TITLE
Chybějící jméno při přihlášení účtem mojeID

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#51]
Při přihlášení účtem mojeID se nenačte jméno uživatele, objednávky Získej kvůli chybějícímu jménu  pak havarují.

Prověřte, prosím, pokud byste to viděli jako problém na straně IdP mojeID, dejte vědět.

**Comment by PetraZabickova** [comment]
duplicita

**Comment by sipek-mzk** [comment]
Problém spočívá ve skutečnosti, že Získej API vyžaduje jako povinné údaje **křestní jméno** a **příjmení** čtenáře.   
Portál knihovny.cz tyto údaje dostává od knihovního systému a jsou případy kdy knihovní systém tyto údaje vrací jako **jeden údaj**, kdy nelze rozlišit co je jméno a co příjmení.   

Navrhované řešení je **upravit Získej API** tak, aby pro **parametr firstname akceptovalo prázdný údaj**.

**Comment by jiripavlik88** [comment]
Pokračujeme v domlouvání ve #52
