### ISSUE TITLE
Chybějící jméno při přihlášení účtem mojeID

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#52]
Při přihlášení účtem mojeID se nenačte jméno uživatele a požadavky na Získej pak havarují.
Prověřte, prosím, pokud byste to viděli jako problém na straně IdP mojeID, dejte vědět.

**Comment by PetraZabickova** [comment]
Ošetříme, jakmile se k tomu dostaneme, je to ve frontě. Problém se týká pouze uživatelů s propojeným účtem.

**Comment by jiripavlik88** [comment]
Perfekt, omylem zadáno duplicitně ke #51 , pardon.

**Comment by jiripavlik88** [comment]
Dejte vědět, prosím, jak budou upravená metadata SPčka CPK v eduID.cz, otestuju. Kdyby to ještě nějak zlobilo, budeme domlouvat k ošetření dále, nicméně s velkou pravděpodobností bude ošetřeno úpravou metadat.

**Comment by jiripavlik88** [comment]
S upravenými metadaty SP CPK už IdPčko mojeID jméno a heslo posílá 👍🏻
