### ISSUE TITLE
Titul není k dispozici

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#54]
Několik e-knih z BOOKPORT je chybně zaindexováno - Titul není k dispozici, např.
https://www.knihovny.cz/Record/7741736494
https://www.knihovny.cz/Record/7741736356
https://www.knihovny.cz/Record/7741736357

**Comment by JanaKurfurstova** [comment]
Dobrý den,

kde se Vám objevily tyto odkazy? Ve výsledcích vyhledávání? Normální odkaz na záznam do Bookportu vypadá např. takhle: https://www.knihovny.cz/Record/bookport.11116

Odkazy na nadřazené záznamy, které nemají prefix zdroje, by se neměly nikde objevovat. Nedaří se nám je ale nikde nalézt a problém replikovat. Můžete prosím napsat, jak jste se k nim dostal (použité fasety, přihlášení apod.)?

Děkuji a zdravím
Jana Kurfürstová

**Comment by jiripavlik88** [comment]
Vidím je po rozkliknutí odkazu na vyhledávání zaslaného e-mailem - https://www.knihovny.cz/short/85d633994

**Comment by JanaKurfurstova** [comment]
Kdy jste ten seznam vyráběl? Není ten mail nějaký starší?

**Comment by jiripavlik88** [comment]
E-mail je zaslaný CPK před necelou hodinou, přeposlal jsem Vám jej.

**Comment by JanaKurfurstova** [comment]
Problém se objevuje jen při počtu výsledků na stránku 50. Dáte-li si 20 výsledků na stránku, odkazy jsou v pořádku. Zjišťujeme příčinu problému.

**Comment by PetraZabickova** [comment]
Opraveno
