### ISSUE TITLE
Chybějící obálky u BOOKPORT

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#56]
U některých e-knih z BOOKPORT chybí obálky, např. https://www.knihovny.cz/Record/bookport.526630404
vs 
https://www.bookport.cz/kniha/treti-ucho-10339/
https://obalkyknih.cz/view?isbn=978-80-275-0822-8+

**Comment by PetraZabickova** [comment]
Čekáme na úpravu na straně obalekknih, aby umožnovali jedním dotazem vrátit obálku i v případě, že záznam obsahuje isbn více než jedno. 

Tuto úpravu jsme požadavali již více než před rokem. Máme přislíbeno, že se tomu budou věnovat.

**Comment by xmorave2** [comment]
Tato úprava již na obálkách proběhla a i u nás je implemnetována.
