### ISSUE TITLE
E-knihy NTK

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#58]
Navrhuji do stránek portálu CPK doplnit odkaz na seznam e-knih NTK - https://sfx.techlib.cz/sfxlcl41/ebooksearch/ntk
Seznam doplní vyhledávání, kde v Zahraniční zdroje lze u e-knih zobrazit dostupnost v NTK, nelze 
ale v CPK zadat vyhledání e-knih ve fondu NTK.

**Comment by JanaKurfurstova** [comment]
Odkazy na SFX indexy jsme při přechodu na novou verzi portálu dávali pryč. Jednak jsme dělali výraznou redukci patičkových stránek, protože patička už přestávala být přehledná, a jednak jsme neviděli velký smysl v odkazování na další nástroje pro další způsob vyhledávání zdrojů, které už lze na portálu vyhledat standardní cestou. 

Pokud už bychom na SFX indexy odkazovali, bylo by to nanejvýš v nějakém již existujícím patičkovém článku. Je otázka, kolik lidí by to tam našlo a mělo by zájem nástroj používat. Odkazují-li na SFX vyhledávač nějaké stránky NTK (respektive KNAV), existují informace o jeho využívanosti?

Určitě neplánujeme SFX vyhledávače upopřeďovat jakkoliv více. Snažíme se portál udržovat z uživatelského hlediska co nejjednodušší. Tj. tuzemské knihovny a zdroje (vč. e-knih) lidé najdou v lokálním indexu a zdroje ze zahraničních odborných databází v centrálním indexu. Aktivně nabízet další způsob vyhledávání v úplně jiném prostředí, který je navíc relevantní jen pro několik jednotlivých knihoven nezapadá do principů, na kterých je portál postavený.

**Comment by jiripavlik88** [comment]
Souhlasím se vzdát funkcionality přehledů dostupných e-knih v knihovnách na úkor přehledosti portálu.

**Comment by jiripavlik88** [comment]
Kompletní seznam e-knih NTK získají čtenáři jinde než v CPK.
