### ISSUE TITLE
LinkSource

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#6]
Linkování na plný text přes LinkSource je nefunkční. Doporučuji zvážit linkování na plné texty přes GetFTR obdobně, jak je implementováno v Mendeley (https://www.mendeley.com/search/).

**Comment by martinkrcal** [comment]
Pro linkování používáme výhradně SFX, Linksource jsme nikdy nepoužívali? Přinesl by nějaké benefity? Lze uvést nějaký příklad? GetFTR budeme dále sledovat, jak se vyvíjí, zatím ho neplánujeme využít, protože podle FAQ na GetFTR ani nemáme jak. Můžeme se o jeho použití a nasazení na portálu více pobavit napřímo. Ideálně bychom k tomu potřebovali více informací a je to na delší debatu.

**Comment by jiripavlik88** [comment]
Jak jsme domlouvali po telefonu, ke GetFTR povyprávím blíž později. Propojím na podporu, vývojáře GetFTR v případě zájmu. Odkazy LinkSource ve výsledních vyhledávání už nevidím, well done.

**Comment by jiripavlik88** [comment]
Odkazy LinkSource ve výsledních vyhledávání u Zahraničních zdrojů se mi opět zobrazují, bohužel.

**Comment by jiripavlik88** [comment]
Ve 2.0.3 již v pořádku.
