### ISSUE TITLE
Deduplikace e-knih Karla Klostermanna

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#60]
E-kniha Ze světa lesních samot není zdeduplikována -
https://www.knihovny.cz/Record/bookport.536699500
https://www.knihovny.cz/Record/mkpe.4323962

obdobně V ráji šumavském -
https://www.knihovny.cz/Record/bookport.528310852
https://www.knihovny.cz/Record/mkpe.4323963

**Comment by JanaKurfurstova** [comment]
Metadata Bookportu nededuplikujeme (viz https://github.com/moravianlibrary/Knihovny.cz/issues/48#issuecomment-1073963532). Totéž se týká Palmknih.

Pokud bychom tam neměli mít MKP e-knihy z Bookportu, pak by je Bookport nesměl mít v exportech. A protože používáme exporty na stejných adresách, které používají i klientské knihovny, tak k takové změně nejspíš Bookport nebude mít důvod (přece jen na to mají navázané další služby jako tvroba uživatelských kolekcí, psaní hodnocení apod.)

**Comment by jiripavlik88** [comment]
Jde o to, že e-knihy jsou volně dostupné (E-knihovna MKP) a součástí fondu KNAV a SVK HK (BOOKPORT).
