### ISSUE TITLE
Zažít Alpy - challenge deduplikace

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#62]
V Cestopisech v Inspiraci je krásná knížka Zažít Alpy -
    https://www.knihovny.cz/Record/kfbz.c5096a35-4b19-4cfc-be6c-472b50e796cd
Knížka je dostupná také v elektronické verzi v BOOKPORT -
     https://www.knihovny.cz/Record/bookport.11764
U tištěné verze ale chybí odkaz na elektronickou v E-verze, aby se čtenář při prokliknutí z Inspirace
dozvěděl o dostupnosti tištěné i elektronické verze.

**Comment by JanaKurfurstova** [comment]
Viz https://github.com/moravianlibrary/Knihovny.cz/issues/48#issuecomment-1073963532
