### ISSUE TITLE
Chybné počty v Adresáři - Projekty

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#64]
V Adresáři - Projekty a Zapojení do projektu jsou uvedeny rozdílné počty u Získej, Knihovny.cz i DNNT. Chybné počty se zdají být v Projekty.

**Comment by xmorave2** [comment]
"Projekty" jsou data pocházející přímo z adresáře a záleží na tom, jak si je knihovny doplňují. Je to volný text a knihovny tam mohou napsat v podstatě cokoliv. V "Zapojení do projektu" jsou námi nějak doplněná data a zásadně přesnější.

**Comment by jiripavlik88** [comment]
Získej, Knihovny.cz a DNNT by asi bylo lepší neuvádět ve fasetě "Projekty", když je knihovny uvádí duplicitně a nepřesně. Nepřebírat tyto hodnoty zadané knihovnami ve volném textu do fasety. Faseta "Zapojení do projektu" je bezva.

**Comment by xmorave2** [comment]
Hodnoty, které se projevují do fasety "Zapojení do projektu" jsou ve fasetě "Projekty" skryté.
