### ISSUE TITLE
Chybné linkování na plné texty článků pro KFBZ

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#65]
Ve výsledních vyhledávání v Zahraničních zdrojích je pro KFBZ řada chybných odkazů na dostupný plný text.

Příklad chybného linkování: 
článek Sweetness is in the ear of the beholder: chord preference across United Kingdom and Pakistani listeners

CPK chybně linkuje do EBSCOhost, kde plný text dostupný není. Plný text článku je dostupný ve [Wiley](https://nyaspubs.onlinelibrary.wiley.com/doi/10.1111/nyas.14655).

![ebscoopenurl](https://user-images.githubusercontent.com/16347996/184397654-1934aeff-b753-4a62-86d8-540dd90d13ad.jpg)

**Comment by JanaKurfurstova** [comment]
KFBZ si ze zdrojů prohledatelných v Zahraničních zdrojích platí jen Ebsco Academic Search Complete (viz https://www.kfbz.cz/databaze-dostupne-uzivatelum-v-knihovne). Tento zdroj mají zapnutý i v SFX. V SFX menu je psáno, že článek není dostupný kvůli embargu.

![Snímek z 2022-08-15 09-44-57](https://user-images.githubusercontent.com/20682569/184596549-4385fdee-6e24-4753-be10-ac542486c161.png)

U všech knihoven s Academic Search Complete je chování tohoto odkazu stejné a nedokážeme jej ovlivnit. Nejde o chybu - knihovna si platí ASC, záznam článku je v ASC, samotný článek má nezávisle na tom embargo a SFX o tom uživatele informuje.

**Comment by jiripavlik88** [comment]
SFX by měl linkovat na dostupný plný text a neukazovat linky na plné texty v embargu. Zatím nevidím, co je potřeba v nastavení u SFX upravit, ještě se na to podívám.

**Comment by jiripavlik88** [comment]
EDS by mělo umět linkovat na Open Access text podobně jako Mendeley - https://www.mendeley.com/catalogue/c359d99e-738e-3695-8bb9-cca1f62290c2/

Zkuste se, prosím , podívat, jestli nepůjde vyladit nastavení linkování na Open Access v EDS. Mendeley k linkování využívá GetFTR.

**Comment by PetraZabickova** [comment]
Linky v embargu ukazují i linkservery institucí, kteří si jej provozují sami a mají ho vyladěny a optimalizovaný. Předpokládám, že pokud by úprava tohoto chování byla možná a snadná, tak by se jim to nechovalo stejným způsobem jako u nás. 

Knihovny, které si předplácejí Wiley Online Library journals, tak se k dokumentu dostanou. Knihovny (např. KFBZ), které si jej nepředplácí, jej zapnutý nemají.  Linkování na Open Accessy často funguje, ale samozřejmě velmi lehce půjde najít takové články, kde se to nedaří. 

V tuto chvíli neplánujeme implementovat GetFTR.  Vzhledem k tomu, že končí období pro které máme aktuální index vysoutěžený, tak další zásadnější úpravy budeme dělat až po té, kdy bude jasné, jaký index budeme používat v budoucnu.

**Comment by PetraZabickova** [comment]
Toto issue zavírám, protože ohlášený problém není jak vyřešit a uživatel je o nedostupnosti dokumentu informován v SFX menu v poznámce.

Na požádání zapnete/upravíme linkování jednotlivým institucím dle jejich potřeb.
