### ISSUE TITLE
Check fulltext availability

### ISSUE THREAD

**Issue by jiripavlik88** [moravianlibrary/Knihovny.cz#7]
Zdá se, že se ověřuje dostupnost plného textu pouze pro NTK, KNAV a Open Access, v anglické verzi se odkaz zobrazuje s návěštím v češtině: "Plný text je dostupný pro uživatele ...". Odkaz na plný text doporučuji otevírat v novém okně.

**Comment by PetraZabickova** [comment]
Otevírání do nového okna přidáme. Ověřujeme i ostatní knihovny. Např. zde:
https://cpk-front.mzk.cz/EdsRecord/edselc,edselc.2-52.0-85051468059

**Comment by jiripavlik88** [comment]
Super, Petro.

**Comment by xmorave2** [comment]
Vyřešeno

**Comment by jiripavlik88** [comment]
Otevírání je v novém okně, ale v anglické verzi se stále zobrazuje "Plný text je dostupný pro uživatele ..."

**Comment by xmorave2** [comment]
Vyřešeno ve vydání [Knihovny.cz 2.0.3](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.3fixVersion)

**Comment by vojtisev** [comment]
Díky, nestálo by za ověření, jak to rozšířit o další nástroje typu https://openaccessbutton.org/ ? Připadá mi, že je to hodně svázané na paywallované články i tam, kde nemusí (jen náhodně testuji na pár článcích)…
