### ISSUE TITLE
Některé knihovny ve fasetu "Katalogy knihoven" jsou uvedeny jako kód

### ISSUE THREAD

**Issue by black23** [moravianlibrary/Knihovny.cz#9]
Některé knihovny ve fasetu "Katlogy knihoven" jsou uvedeny jako kód, ne člověku pochopitelným názvem:
![obrazek](https://user-images.githubusercontent.com/5516936/148359817-e2070ad5-fd92-4071-9d55-e4b7d9881056.png)

**Comment by xmorave2** [comment]
Před ostrým nasazením to budeme aktualizovat. Ale nechtěli jsme přerušit zapojování nových knihoven, tak to není zatím 100% aktuální.

**Comment by xmorave2** [comment]
Opraveno ve vydání [Knihovny.cz 2.0.7](https://github.com/moravianlibrary/Knihovny.cz/releases/tag/v2.0.7)
